/**
 * @file business-rules.mock.ts
 * @description Datos mock realistas para HU-131 — Motor de Reglas de Negocio 4GUARD WMS.
 */

import { BusinessRule } from './business-rules.models';

export const MOCK_BUSINESS_RULES: BusinessRule[] = [
  {
    id: 'rule-01',
    code: 'PICKING_STRATEGY',
    name: 'Estrategia de Despacho e Rotación en Almacén',
    description: 'Define el algoritmo de rotación física de inventario para tareas de picking y despacho.',
    module: 'SHIPPING',
    category: 'STRATEGY',
    functionalType: 'DETERMINISTIC',
    dataType: 'ENUM',
    value: 'FEFO',
    options: ['FEFO', 'FIFO', 'LIFO', 'LEFO'],
    scope: 'WAREHOUSE',
    scopeEntityName: 'BR-TOL-01 — Toluca',
    status: 'ACTIVE',
    severity: 'CRITICAL',
    effectiveDate: '2026-01-01',
    lastModifiedAt: '2026-07-23T18:45:00Z',
    lastModifiedBy: 'carlos.lopez@4guard.mx',
    changeReason: 'Alineación con políticas de rotación de producto perecedero Q3.',
    isSystem: true,
  },
  {
    id: 'rule-02',
    code: 'RECEIVING_WEIGHT_TOLERANCE',
    name: 'Tolerancia Máxima en Pesaje de Recepción',
    description: 'Porcentaje de variación permitido entre el peso teórico en ASN y el pesaje real en andén.',
    module: 'RECEIVING',
    category: 'TOLERANCE',
    functionalType: 'THRESHOLD',
    dataType: 'PERCENTAGE',
    value: 2.5,
    unit: '%',
    minValue: 0.0,
    maxValue: 10.0,
    scope: 'ORGANIZATION',
    scopeEntityName: 'Corporativo SynexIA',
    status: 'ACTIVE',
    severity: 'MEDIUM',
    effectiveDate: '2026-02-15',
    lastModifiedAt: '2026-07-22T14:10:00Z',
    lastModifiedBy: 'laura.mendoza@4guard.mx',
    changeReason: 'Ajuste operativo a solicitud de auditoría de inventarios.',
    isSystem: false,
  },
  {
    id: 'rule-03',
    code: 'ALLOW_RECEIPT_WITHOUT_ASN',
    name: 'Permitir Entradas Ciegas sin Orden/ASN Previas',
    description: 'Habilita la recepción directa de mercancía en andén sin documento ASN registrado previa validación.',
    module: 'RECEIVING',
    category: 'RESTRICTION',
    functionalType: 'POLICY',
    dataType: 'BOOLEAN',
    value: false,
    scope: 'GLOBAL',
    status: 'ACTIVE',
    severity: 'CRITICAL',
    effectiveDate: '2026-01-01',
    lastModifiedAt: '2026-07-15T09:30:00Z',
    lastModifiedBy: 'enrique.archundia@4guard.mx',
    changeReason: 'Bloqueo estricto por directiva de control de prevención de pérdidas.',
    isSystem: true,
  },
  {
    id: 'rule-04',
    code: 'EXPIRATION_WARNING_DAYS',
    name: 'Ventana de Alerta de Próxima Caducidad',
    description: 'Días previos a la fecha de caducidad en que el lote entra en estado de advertencia previa a cuarentena.',
    module: 'INVENTORY',
    category: 'ALERT',
    functionalType: 'THRESHOLD',
    dataType: 'DAYS',
    value: 30,
    unit: 'días',
    minValue: 1,
    maxValue: 180,
    scope: 'WAREHOUSE',
    scopeEntityName: 'BR-TOL-01 — Toluca',
    status: 'ACTIVE',
    severity: 'HIGH',
    effectiveDate: '2026-03-01',
    lastModifiedAt: '2026-07-20T11:20:00Z',
    lastModifiedBy: 'carlos.lopez@4guard.mx',
    changeReason: 'Incremento de ventana preventiva para productos farmacéuticos.',
    isSystem: false,
  },
  {
    id: 'rule-05',
    code: 'SESSION_IDLE_MINUTES',
    name: 'Tiempo Límite de Inactividad de Sesión',
    description: 'Minutos de inactividad continuos antes de cerrar automáticamente la sesión de la consola.',
    module: 'SECURITY',
    category: 'TIMING',
    functionalType: 'POLICY',
    dataType: 'DURATION_MINUTES',
    value: 15,
    unit: 'minutos',
    minValue: 5,
    maxValue: 120,
    scope: 'GLOBAL',
    status: 'ACTIVE',
    severity: 'INFO',
    effectiveDate: '2026-01-01',
    lastModifiedAt: '2026-06-10T16:00:00Z',
    lastModifiedBy: 'enrique.archundia@4guard.mx',
    changeReason: 'Estándar global de ciberseguridad para terminales de almacén.',
    isSystem: true,
  },
  {
    id: 'rule-06',
    code: 'TRUCK_WAIT_ALERT',
    name: 'Tiempo Máximo de Espera de Camiones en Andén',
    description: 'Tiempo límite en minutos de estadía de transporte en patio antes de emitir alerta crítica al Supervisor.',
    module: 'RECEIVING',
    category: 'TIMING',
    functionalType: 'THRESHOLD',
    dataType: 'DURATION_MINUTES',
    value: 45,
    unit: 'minutos',
    minValue: 10,
    maxValue: 240,
    scope: 'WAREHOUSE',
    scopeEntityName: 'BR-MTY-02 — Monterrey',
    status: 'ACTIVE',
    severity: 'WARNING',
    effectiveDate: '2026-04-01',
    lastModifiedAt: '2026-07-23T10:00:00Z',
    lastModifiedBy: 'roberto.gomez@4guard.mx',
    changeReason: 'Optimización de indicador Dwell Time en patio de maniobras.',
    isSystem: false,
  },
  {
    id: 'rule-07',
    code: 'AUTO_QUARANTINE',
    name: 'Cuarentena Automática por Rechazo en Inspección',
    description: 'Aplica bloqueo de stock automático al detectar un rechazo en muestreo de control de calidad.',
    module: 'QUALITY',
    category: 'AUTOMATION',
    functionalType: 'VALIDATION',
    dataType: 'BOOLEAN',
    value: true,
    scope: 'CLIENT_WAREHOUSE',
    scopeEntityName: 'PharmaCorp × Toluca',
    status: 'ACTIVE',
    severity: 'CRITICAL',
    effectiveDate: '2026-01-15',
    lastModifiedAt: '2026-07-18T13:40:00Z',
    lastModifiedBy: 'laura.mendoza@4guard.mx',
    changeReason: 'Requisito normativo de Cofepris para productos grado médico.',
    isSystem: false,
  },
  {
    id: 'rule-08',
    code: 'MAX_PALLET_STACK_HEIGHT',
    name: 'Altura Máxima de Apilamiento de Pallets',
    description: 'Restricción de seguridad que limita la cantidad de niveles permitidos en racks de almacenaje.',
    module: 'LAYOUT',
    category: 'RESTRICTION',
    functionalType: 'THRESHOLD',
    dataType: 'NUMBER',
    value: 3,
    unit: 'niveles',
    minValue: 1,
    maxValue: 5,
    scope: 'WAREHOUSE',
    scopeEntityName: 'BR-GDL-03 — Guadalajara',
    status: 'ACTIVE',
    severity: 'HIGH',
    effectiveDate: '2026-02-01',
    lastModifiedAt: '2026-07-12T08:15:00Z',
    lastModifiedBy: 'carlos.lopez@4guard.mx',
    changeReason: 'Ajuste estructural por normatividad de protección civil.',
    isSystem: false,
  },
  {
    id: 'rule-09',
    code: 'CYCLE_COUNT_DISCREPANCY_THRESHOLD',
    name: 'Tolerancia de Discrepancia en Conteo Cíclico',
    description: 'Porcentaje máximo de variación física vs sistema que requiere aprobación de Gerencia.',
    module: 'INVENTORY',
    category: 'TOLERANCE',
    functionalType: 'THRESHOLD',
    dataType: 'PERCENTAGE',
    value: 1.0,
    unit: '%',
    minValue: 0.1,
    maxValue: 5.0,
    scope: 'ORGANIZATION',
    scopeEntityName: 'Corporativo SynexIA',
    status: 'ACTIVE',
    severity: 'CRITICAL',
    effectiveDate: '2026-01-01',
    lastModifiedAt: '2026-07-21T17:50:00Z',
    lastModifiedBy: 'enrique.archundia@4guard.mx',
    changeReason: 'Fortalecimiento de control de discrepancias en conteos diarios.',
    isSystem: false,
  },
  {
    id: 'rule-10',
    code: 'STAGING_BAY_MAX_DWELL_HOURS',
    name: 'Tiempo Máximo de Mercancía en Zona Staging',
    description: 'Horas máximas de permanencia de pallets en andén antes de generar orden de acomodo prioritaria.',
    module: 'SHIPPING',
    category: 'TIMING',
    functionalType: 'THRESHOLD',
    dataType: 'NUMBER',
    value: 4,
    unit: 'horas',
    minValue: 1,
    maxValue: 24,
    scope: 'WAREHOUSE',
    scopeEntityName: 'BR-TOL-01 — Toluca',
    status: 'INACTIVE',
    severity: 'MEDIUM',
    effectiveDate: '2026-05-01',
    lastModifiedAt: '2026-07-05T09:10:00Z',
    lastModifiedBy: 'carlos.lopez@4guard.mx',
    changeReason: 'Pausa temporal durante reorganización de andenes.',
    isSystem: false,
  },
];
