/**
 * @file user-activity.mock.ts
 * @description Datos dummy para HU-146 — Reporte de Actividad por Usuario.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * PROPÓSITO
 * ═══════════════════════════════════════════════════════════════════════════
 * Proporcionar 25+ eventos realistas y 4 perfiles de reporte de muestra
 * para evaluar el diseño, la UX y los filtros sin backend real.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * NOTA
 * ═══════════════════════════════════════════════════════════════════════════
 * Eliminar este archivo cuando el endpoint /api/user-activity/events esté
 * disponible y el servicio utilice HTTP real.
 */

import { UserActivityEvent, ActivityReportProfile } from './user-activity.models';

// ─────────────────────────────────────────────────────────────────────────────
// EVENTOS DE ACTIVIDAD (25 eventos variados)
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_ACTIVITY_EVENTS: UserActivityEvent[] = [
  // 1 — Login exitoso (dentro de horario)
  {
    id: 'evt-001',
    occurredAt: '2026-07-23T08:01:00Z',
    userId: 'usr-01',
    userName: 'Carlos López',
    userEmail: 'carlos.lopez@4guard.mx',
    userRole: 'OPERATIONS_SUPERVISOR',
    organizationId: 'org-01',
    warehouseId: 'wh-01',
    warehouseName: 'Toluca',
    shiftId: 'sh-01',
    shiftName: 'Turno Matutino',
    module: 'Autenticación',
    action: 'LOGIN',
    entityType: 'Sesión de usuario',
    entityId: 'ses-abc001',
    description: 'Inicio de sesión exitoso desde Chrome/Windows.',
    result: 'SUCCESS',
    severity: 'INFO',
    ipAddress: '192.168.1.45',
    device: 'Desktop',
    browser: 'Chrome 126',
    sessionId: 'ses-abc001',
    correlationId: 'cor-001',
    durationMs: 312,
    outsideShift: false,
  },

  // 2 — Creación de recepción
  {
    id: 'evt-002',
    occurredAt: '2026-07-23T08:09:00Z',
    userId: 'usr-01',
    userName: 'Carlos López',
    userEmail: 'carlos.lopez@4guard.mx',
    userRole: 'OPERATIONS_SUPERVISOR',
    organizationId: 'org-01',
    warehouseId: 'wh-01',
    warehouseName: 'Toluca',
    shiftId: 'sh-01',
    shiftName: 'Turno Matutino',
    module: 'Recepción',
    action: 'CREATE_RECEIPT',
    entityType: 'ASN',
    entityId: 'ASN-00321',
    description: 'Creó recepción ASN-00321 con 48 líneas de producto.',
    result: 'SUCCESS',
    severity: 'INFO',
    newValues: { asn: 'ASN-00321', lines: 48, status: 'OPEN' },
    ipAddress: '192.168.1.45',
    device: 'Desktop',
    browser: 'Chrome 126',
    sessionId: 'ses-abc001',
    correlationId: 'cor-002',
    durationMs: 823,
    outsideShift: false,
  },

  // 3 — Registro de lote
  {
    id: 'evt-003',
    occurredAt: '2026-07-23T08:26:00Z',
    userId: 'usr-01',
    userName: 'Carlos López',
    userEmail: 'carlos.lopez@4guard.mx',
    userRole: 'OPERATIONS_SUPERVISOR',
    organizationId: 'org-01',
    warehouseId: 'wh-01',
    warehouseName: 'Toluca',
    shiftId: 'sh-01',
    shiftName: 'Turno Matutino',
    module: 'Recepción',
    action: 'CREATE_RECEIPT',
    entityType: 'Lote',
    entityId: 'LOT-2207',
    description: 'Registró lote LOT-2207 para SKU NES-CAFE-001.',
    result: 'SUCCESS',
    severity: 'INFO',
    newValues: { lot: 'LOT-2207', sku: 'NES-CAFE-001', qty: 240 },
    ipAddress: '192.168.1.45',
    device: 'Desktop',
    browser: 'Chrome 126',
    sessionId: 'ses-abc001',
    correlationId: 'cor-003',
    durationMs: 512,
    outsideShift: false,
  },

  // 4 — Movimiento de inventario
  {
    id: 'evt-004',
    occurredAt: '2026-07-23T08:43:00Z',
    userId: 'usr-01',
    userName: 'Carlos López',
    userEmail: 'carlos.lopez@4guard.mx',
    userRole: 'OPERATIONS_SUPERVISOR',
    organizationId: 'org-01',
    warehouseId: 'wh-01',
    warehouseName: 'Toluca',
    shiftId: 'sh-01',
    shiftName: 'Turno Matutino',
    module: 'Inventario',
    action: 'MOVE_STOCK',
    entityType: 'SKU',
    entityId: 'NES-CAFE-001',
    description: 'Movió inventario de SKU NES-CAFE-001 de ubicación A-01-02 a B-03-01.',
    result: 'SUCCESS',
    severity: 'INFO',
    previousValues: { location: 'A-01-02', qty: 240 },
    newValues: { location: 'B-03-01', qty: 240 },
    ipAddress: '192.168.1.45',
    device: 'Desktop',
    browser: 'Chrome 126',
    sessionId: 'ses-abc001',
    correlationId: 'cor-004',
    durationMs: 674,
    outsideShift: false,
  },

  // 5 — Bloqueo de lote (HIGH)
  {
    id: 'evt-005',
    occurredAt: '2026-07-23T09:15:00Z',
    userId: 'usr-02',
    userName: 'Laura Martínez',
    userEmail: 'laura.martinez@4guard.mx',
    userRole: 'SHIFT_LEADER',
    organizationId: 'org-01',
    warehouseId: 'wh-02',
    warehouseName: 'Monterrey',
    shiftId: 'sh-02',
    shiftName: 'Turno Vespertino',
    clientId: 'cli-01',
    clientName: 'Nestlé México',
    module: 'Calidad',
    action: 'BLOCK_LOT',
    entityType: 'Lote',
    entityId: 'LOT-240722',
    description: 'Bloqueó lote LOT-240722 por empaque dañado detectado en inspección visual.',
    result: 'SUCCESS',
    severity: 'HIGH',
    previousValues: { status: 'APPROVED', location: 'A-01-02' },
    newValues: { status: 'BLOCKED', location: 'QA-03' },
    reason: 'Empaque dañado en inspección visual',
    ipAddress: '192.168.10.88',
    device: 'Tablet',
    browser: 'Safari 17',
    sessionId: 'ses-def002',
    correlationId: 'cor-005',
    durationMs: 1240,
    outsideShift: false,
  },

  // 6 — Login fallido (MEDIUM)
  {
    id: 'evt-006',
    occurredAt: '2026-07-23T09:30:00Z',
    userId: 'usr-03',
    userName: 'Pedro Sánchez',
    userEmail: 'pedro.sanchez@4guard.mx',
    userRole: 'OPERATIONS_MANAGER',
    organizationId: 'org-01',
    warehouseId: 'wh-01',
    warehouseName: 'Toluca',
    module: 'Autenticación',
    action: 'LOGIN_FAILED',
    entityType: 'Cuenta de usuario',
    entityId: 'usr-03',
    description: 'Intento de inicio de sesión fallido. Credenciales incorrectas (intento 2/5).',
    result: 'REJECTED',
    severity: 'MEDIUM',
    reason: 'Credenciales incorrectas',
    ipAddress: '10.0.0.12',
    device: 'Desktop',
    browser: 'Firefox 127',
    sessionId: 'ses-ghi003',
    correlationId: 'cor-006',
    durationMs: 220,
    outsideShift: false,
  },

  // 7 — Cancelación de embarque (CRITICAL)
  {
    id: 'evt-007',
    occurredAt: '2026-07-23T09:45:00Z',
    userId: 'usr-04',
    userName: 'Andrea Torres',
    userEmail: 'andrea.torres@4guard.mx',
    userRole: 'SHIFT_LEADER',
    organizationId: 'org-01',
    warehouseId: 'wh-03',
    warehouseName: 'Guadalajara',
    shiftId: 'sh-01',
    shiftName: 'Turno Matutino',
    module: 'Embarques',
    action: 'CANCEL_SHIPMENT',
    entityType: 'Embarque',
    entityId: 'SHP-00982',
    description: 'Canceló embarque SHP-00982 por falta de unidad de transporte.',
    result: 'SUCCESS',
    severity: 'CRITICAL',
    previousValues: { status: 'SCHEDULED' },
    newValues: { status: 'CANCELLED' },
    reason: 'Falta de unidad de transporte',
    ipAddress: '172.16.0.55',
    device: 'Desktop',
    browser: 'Chrome 126',
    sessionId: 'ses-jkl004',
    correlationId: 'cor-007',
    durationMs: 980,
    outsideShift: false,
  },

  // 8 — Actualización de proveedor (MEDIUM)
  {
    id: 'evt-008',
    occurredAt: '2026-07-23T10:02:00Z',
    userId: 'usr-05',
    userName: 'Luis Hernández',
    userEmail: 'luis.hernandez@4guard.mx',
    userRole: 'OPERATIONS_SUPERVISOR',
    organizationId: 'org-01',
    warehouseId: 'wh-01',
    warehouseName: 'Toluca',
    module: 'Proveedores',
    action: 'UPDATE_SUPPLIER',
    entityType: 'Proveedor',
    entityId: 'SUP-019',
    description: 'Actualizó datos de contacto del proveedor SUP-019.',
    result: 'SUCCESS',
    severity: 'MEDIUM',
    previousValues: { phone: '555-1000', email: 'old@proveedor.mx' },
    newValues: { phone: '555-2000', email: 'new@proveedor.mx' },
    ipAddress: '192.168.1.50',
    device: 'Desktop',
    browser: 'Edge 125',
    sessionId: 'ses-mno005',
    correlationId: 'cor-008',
    durationMs: 450,
    outsideShift: false,
  },

  // 9 — Logout
  {
    id: 'evt-009',
    occurredAt: '2026-07-23T10:11:00Z',
    userId: 'usr-01',
    userName: 'Carlos López',
    userEmail: 'carlos.lopez@4guard.mx',
    userRole: 'OPERATIONS_SUPERVISOR',
    organizationId: 'org-01',
    warehouseId: 'wh-01',
    warehouseName: 'Toluca',
    module: 'Autenticación',
    action: 'LOGOUT',
    entityType: 'Sesión de usuario',
    entityId: 'ses-abc001',
    description: 'Cierre de sesión exitoso.',
    result: 'SUCCESS',
    severity: 'INFO',
    ipAddress: '192.168.1.45',
    device: 'Desktop',
    browser: 'Chrome 126',
    sessionId: 'ses-abc001',
    correlationId: 'cor-009',
    durationMs: 120,
    outsideShift: false,
  },

  // 10 — Ajuste de inventario (HIGH)
  {
    id: 'evt-010',
    occurredAt: '2026-07-23T10:30:00Z',
    userId: 'usr-06',
    userName: 'Fernanda Ruiz',
    userEmail: 'fernanda.ruiz@4guard.mx',
    userRole: 'OPERATIONS_MANAGER',
    organizationId: 'org-01',
    warehouseId: 'wh-02',
    warehouseName: 'Monterrey',
    module: 'Inventario',
    action: 'ADJUST_INVENTORY',
    entityType: 'SKU',
    entityId: 'MXC-SAL-005',
    description: 'Ajuste de inventario negativo de -12 unidades en SKU MXC-SAL-005.',
    result: 'SUCCESS',
    severity: 'HIGH',
    previousValues: { qty: 150, unit: 'PZA' },
    newValues: { qty: 138, unit: 'PZA' },
    reason: 'Merma detectada en conteo físico',
    ipAddress: '10.0.1.20',
    device: 'Desktop',
    browser: 'Chrome 126',
    sessionId: 'ses-pqr006',
    correlationId: 'cor-010',
    durationMs: 734,
    outsideShift: false,
  },

  // 11 — Error de autorización
  {
    id: 'evt-011',
    occurredAt: '2026-07-23T11:00:00Z',
    userId: 'usr-05',
    userName: 'Luis Hernández',
    userEmail: 'luis.hernandez@4guard.mx',
    userRole: 'OPERATIONS_SUPERVISOR',
    organizationId: 'org-01',
    warehouseId: 'wh-01',
    warehouseName: 'Toluca',
    module: 'Usuarios',
    action: 'AUTHORIZATION_ERROR',
    entityType: 'Módulo de Usuarios',
    description: 'Intento de acceso al módulo de gestión de usuarios sin permisos suficientes.',
    result: 'ERROR',
    severity: 'MEDIUM',
    reason: 'Permisos insuficientes para USERS_WRITE',
    ipAddress: '192.168.1.50',
    device: 'Desktop',
    browser: 'Edge 125',
    sessionId: 'ses-mno005',
    correlationId: 'cor-011',
    durationMs: 88,
    outsideShift: false,
  },

  // 12 — Picking confirmado
  {
    id: 'evt-012',
    occurredAt: '2026-07-23T11:20:00Z',
    userId: 'usr-04',
    userName: 'Andrea Torres',
    userEmail: 'andrea.torres@4guard.mx',
    userRole: 'SHIFT_LEADER',
    organizationId: 'org-01',
    warehouseId: 'wh-03',
    warehouseName: 'Guadalajara',
    shiftId: 'sh-01',
    shiftName: 'Turno Matutino',
    module: 'Picking',
    action: 'CONFIRM_PICKING',
    entityType: 'Orden de Picking',
    entityId: 'PCK-00445',
    description: 'Confirmó orden de picking PCK-00445 con 32 líneas completadas.',
    result: 'SUCCESS',
    severity: 'INFO',
    newValues: { order: 'PCK-00445', lines: 32, status: 'COMPLETED' },
    ipAddress: '172.16.0.55',
    device: 'Desktop',
    browser: 'Chrome 126',
    sessionId: 'ses-jkl004',
    correlationId: 'cor-012',
    durationMs: 560,
    outsideShift: false,
  },

  // 13 — Exportación de reporte
  {
    id: 'evt-013',
    occurredAt: '2026-07-23T11:45:00Z',
    userId: 'usr-03',
    userName: 'Pedro Sánchez',
    userEmail: 'pedro.sanchez@4guard.mx',
    userRole: 'OPERATIONS_MANAGER',
    organizationId: 'org-01',
    warehouseId: 'wh-01',
    warehouseName: 'Toluca',
    module: 'Reportes',
    action: 'EXPORT_REPORT',
    entityType: 'Reporte de Inventario',
    entityId: 'RPT-INV-20260723',
    description: 'Exportó reporte de inventario en formato XLSX con 1,284 registros.',
    result: 'SUCCESS',
    severity: 'INFO',
    newValues: { format: 'XLSX', records: 1284 },
    ipAddress: '10.0.0.12',
    device: 'Desktop',
    browser: 'Firefox 127',
    sessionId: 'ses-ghi003',
    correlationId: 'cor-013',
    durationMs: 3200,
    outsideShift: false,
  },

  // 14 — Actividad fuera de horario (MEDIUM) — antes de 06:00
  {
    id: 'evt-014',
    occurredAt: '2026-07-23T04:15:00Z',
    userId: 'usr-02',
    userName: 'Laura Martínez',
    userEmail: 'laura.martinez@4guard.mx',
    userRole: 'SHIFT_LEADER',
    organizationId: 'org-01',
    warehouseId: 'wh-02',
    warehouseName: 'Monterrey',
    module: 'Inventario',
    action: 'ADJUST_INVENTORY',
    entityType: 'SKU',
    entityId: 'KIM-LIM-003',
    description: 'Ajuste de inventario ejecutado fuera del horario de turno normal.',
    result: 'SUCCESS',
    severity: 'MEDIUM',
    previousValues: { qty: 88 },
    newValues: { qty: 80 },
    reason: 'Conteo nocturno especial',
    ipAddress: '192.168.10.88',
    device: 'Tablet',
    browser: 'Safari 17',
    sessionId: 'ses-stu007',
    correlationId: 'cor-014',
    durationMs: 420,
    outsideShift: true,
  },

  // 15 — Cambio de ubicación (HIGH)
  {
    id: 'evt-015',
    occurredAt: '2026-07-23T12:00:00Z',
    userId: 'usr-06',
    userName: 'Fernanda Ruiz',
    userEmail: 'fernanda.ruiz@4guard.mx',
    userRole: 'OPERATIONS_MANAGER',
    organizationId: 'org-01',
    warehouseId: 'wh-02',
    warehouseName: 'Monterrey',
    module: 'Layout',
    action: 'CHANGE_LOCATION',
    entityType: 'Ubicación',
    entityId: 'LOC-A01-05',
    description: 'Cambió tipo de ubicación de BULK a PICKING en zona A.',
    result: 'SUCCESS',
    severity: 'HIGH',
    previousValues: { type: 'BULK', zone: 'A' },
    newValues: { type: 'PICKING', zone: 'A' },
    reason: 'Reestructuración de zonas por demanda de picking',
    ipAddress: '10.0.1.20',
    device: 'Desktop',
    browser: 'Chrome 126',
    sessionId: 'ses-pqr006',
    correlationId: 'cor-015',
    durationMs: 890,
    outsideShift: false,
  },

  // 16 — Cambio de rol (CRITICAL)
  {
    id: 'evt-016',
    occurredAt: '2026-07-23T12:30:00Z',
    userId: 'usr-03',
    userName: 'Pedro Sánchez',
    userEmail: 'pedro.sanchez@4guard.mx',
    userRole: 'OPERATIONS_MANAGER',
    organizationId: 'org-01',
    warehouseId: 'wh-01',
    warehouseName: 'Toluca',
    module: 'Usuarios',
    action: 'CHANGE_ROLE',
    entityType: 'Usuario',
    entityId: 'usr-05',
    description: 'Cambió rol de Luis Hernández de OPERATIONS_SUPERVISOR a SHIFT_LEADER.',
    result: 'SUCCESS',
    severity: 'CRITICAL',
    previousValues: { role: 'OPERATIONS_SUPERVISOR' },
    newValues: { role: 'SHIFT_LEADER' },
    reason: 'Reorganización de turnos Q3 2026',
    ipAddress: '10.0.0.12',
    device: 'Desktop',
    browser: 'Firefox 127',
    sessionId: 'ses-ghi003',
    correlationId: 'cor-016',
    durationMs: 1100,
    outsideShift: false,
  },

  // 17 — Login exitoso Laura (Monterrey)
  {
    id: 'evt-017',
    occurredAt: '2026-07-23T14:00:00Z',
    userId: 'usr-02',
    userName: 'Laura Martínez',
    userEmail: 'laura.martinez@4guard.mx',
    userRole: 'SHIFT_LEADER',
    organizationId: 'org-01',
    warehouseId: 'wh-02',
    warehouseName: 'Monterrey',
    module: 'Autenticación',
    action: 'LOGIN',
    entityType: 'Sesión de usuario',
    entityId: 'ses-vwx008',
    description: 'Inicio de sesión exitoso para turno vespertino.',
    result: 'SUCCESS',
    severity: 'INFO',
    ipAddress: '192.168.10.88',
    device: 'Tablet',
    browser: 'Safari 17',
    sessionId: 'ses-vwx008',
    correlationId: 'cor-017',
    durationMs: 290,
    outsideShift: false,
  },

  // 18 — Inspección de calidad aprobada
  {
    id: 'evt-018',
    occurredAt: '2026-07-23T14:30:00Z',
    userId: 'usr-01',
    userName: 'Carlos López',
    userEmail: 'carlos.lopez@4guard.mx',
    userRole: 'OPERATIONS_SUPERVISOR',
    organizationId: 'org-01',
    warehouseId: 'wh-01',
    warehouseName: 'Toluca',
    module: 'Calidad',
    action: 'CONFIRM_PICKING',
    entityType: 'Inspección',
    entityId: 'INS-0088',
    description: 'Aprobó inspección de calidad INS-0088 para recepción ASN-00321.',
    result: 'SUCCESS',
    severity: 'INFO',
    newValues: { inspection: 'INS-0088', result: 'APPROVED' },
    ipAddress: '192.168.1.45',
    device: 'Desktop',
    browser: 'Chrome 126',
    sessionId: 'ses-abc009',
    correlationId: 'cor-018',
    durationMs: 640,
    outsideShift: false,
  },

  // 19 — Error en embarque (ERROR)
  {
    id: 'evt-019',
    occurredAt: '2026-07-23T15:00:00Z',
    userId: 'usr-04',
    userName: 'Andrea Torres',
    userEmail: 'andrea.torres@4guard.mx',
    userRole: 'SHIFT_LEADER',
    organizationId: 'org-01',
    warehouseId: 'wh-03',
    warehouseName: 'Guadalajara',
    module: 'Embarques',
    action: 'CANCEL_SHIPMENT',
    entityType: 'Embarque',
    entityId: 'SHP-00991',
    description: 'Error al intentar cancelar embarque SHP-00991. El sistema rechazó la operación.',
    result: 'ERROR',
    severity: 'HIGH',
    reason: 'Embarque ya en tránsito — no se puede cancelar',
    ipAddress: '172.16.0.55',
    device: 'Desktop',
    browser: 'Chrome 126',
    sessionId: 'ses-jkl010',
    correlationId: 'cor-019',
    durationMs: 350,
    outsideShift: false,
  },

  // 20 — Actualización de proveedor (WARNING)
  {
    id: 'evt-020',
    occurredAt: '2026-07-23T15:20:00Z',
    userId: 'usr-05',
    userName: 'Luis Hernández',
    userEmail: 'luis.hernandez@4guard.mx',
    userRole: 'OPERATIONS_SUPERVISOR',
    organizationId: 'org-01',
    warehouseId: 'wh-01',
    warehouseName: 'Toluca',
    module: 'Proveedores',
    action: 'UPDATE_SUPPLIER',
    entityType: 'Proveedor',
    entityId: 'SUP-024',
    description: 'Actualizó condiciones de pago de SUP-024. Advertencia: crédito vencido.',
    result: 'WARNING',
    severity: 'MEDIUM',
    previousValues: { paymentTerms: 'NET30' },
    newValues: { paymentTerms: 'NET60' },
    reason: 'Advertencia de crédito vencido registrada',
    ipAddress: '192.168.1.50',
    device: 'Desktop',
    browser: 'Edge 125',
    sessionId: 'ses-mno011',
    correlationId: 'cor-020',
    durationMs: 530,
    outsideShift: false,
  },

  // 21 — Actividad fuera de horario — tarde noche
  {
    id: 'evt-021',
    occurredAt: '2026-07-22T23:10:00Z',
    userId: 'usr-06',
    userName: 'Fernanda Ruiz',
    userEmail: 'fernanda.ruiz@4guard.mx',
    userRole: 'OPERATIONS_MANAGER',
    organizationId: 'org-01',
    warehouseId: 'wh-02',
    warehouseName: 'Monterrey',
    module: 'Reportes',
    action: 'EXPORT_REPORT',
    entityType: 'Reporte de Actividad',
    entityId: 'RPT-ACT-20260722',
    description: 'Exportó reporte de actividad nocturno en PDF.',
    result: 'SUCCESS',
    severity: 'INFO',
    newValues: { format: 'PDF', records: 412 },
    ipAddress: '10.0.1.20',
    device: 'Desktop',
    browser: 'Chrome 126',
    sessionId: 'ses-pqr012',
    correlationId: 'cor-021',
    durationMs: 2800,
    outsideShift: true,
  },

  // 22 — Login fallido (tercer intento)
  {
    id: 'evt-022',
    occurredAt: '2026-07-23T16:00:00Z',
    userId: 'usr-02',
    userName: 'Laura Martínez',
    userEmail: 'laura.martinez@4guard.mx',
    userRole: 'SHIFT_LEADER',
    organizationId: 'org-01',
    warehouseId: 'wh-02',
    warehouseName: 'Monterrey',
    module: 'Autenticación',
    action: 'LOGIN_FAILED',
    entityType: 'Cuenta de usuario',
    entityId: 'usr-02',
    description: 'Tercer intento de inicio de sesión fallido. Cuenta en riesgo de bloqueo.',
    result: 'REJECTED',
    severity: 'HIGH',
    reason: 'Contraseña incorrecta — intento 3/5',
    ipAddress: '192.168.10.89',
    device: 'Mobile',
    browser: 'Safari 17',
    sessionId: 'ses-yz-013',
    correlationId: 'cor-022',
    durationMs: 195,
    outsideShift: false,
  },

  // 23 — Ajuste crítico de inventario
  {
    id: 'evt-023',
    occurredAt: '2026-07-23T16:30:00Z',
    userId: 'usr-03',
    userName: 'Pedro Sánchez',
    userEmail: 'pedro.sanchez@4guard.mx',
    userRole: 'OPERATIONS_MANAGER',
    organizationId: 'org-01',
    warehouseId: 'wh-01',
    warehouseName: 'Toluca',
    module: 'Inventario',
    action: 'CRITICAL_ACTION',
    entityType: 'SKU',
    entityId: 'ABB-BOT-010',
    description: 'Liberó cuarentena de lote crítico ABB-BOT-010 tras segunda inspección.',
    result: 'SUCCESS',
    severity: 'CRITICAL',
    previousValues: { status: 'QUARANTINE' },
    newValues: { status: 'AVAILABLE' },
    reason: 'Segunda inspección aprobada por laboratorio externo',
    ipAddress: '10.0.0.12',
    device: 'Desktop',
    browser: 'Firefox 127',
    sessionId: 'ses-ghi003',
    correlationId: 'cor-023',
    durationMs: 1580,
    outsideShift: false,
  },

  // 24 — Actividad fuera de horario (madrugada)
  {
    id: 'evt-024',
    occurredAt: '2026-07-23T05:30:00Z',
    userId: 'usr-05',
    userName: 'Luis Hernández',
    userEmail: 'luis.hernandez@4guard.mx',
    userRole: 'OPERATIONS_SUPERVISOR',
    organizationId: 'org-01',
    warehouseId: 'wh-01',
    warehouseName: 'Toluca',
    module: 'Inventario',
    action: 'MOVE_STOCK',
    entityType: 'SKU',
    entityId: 'NES-CAFE-001',
    description: 'Movimiento de stock ejecutado antes del inicio del turno matutino.',
    result: 'SUCCESS',
    severity: 'MEDIUM',
    previousValues: { location: 'B-03-01' },
    newValues: { location: 'C-02-04' },
    reason: 'Preparación para recepción temprana',
    ipAddress: '192.168.1.50',
    device: 'Desktop',
    browser: 'Edge 125',
    sessionId: 'ses-early014',
    correlationId: 'cor-024',
    durationMs: 670,
    outsideShift: true,
  },

  // 25 — Logout Fernanda Ruiz
  {
    id: 'evt-025',
    occurredAt: '2026-07-23T17:00:00Z',
    userId: 'usr-06',
    userName: 'Fernanda Ruiz',
    userEmail: 'fernanda.ruiz@4guard.mx',
    userRole: 'OPERATIONS_MANAGER',
    organizationId: 'org-01',
    warehouseId: 'wh-02',
    warehouseName: 'Monterrey',
    module: 'Autenticación',
    action: 'LOGOUT',
    entityType: 'Sesión de usuario',
    entityId: 'ses-pqr006',
    description: 'Cierre de sesión al finalizar turno.',
    result: 'SUCCESS',
    severity: 'INFO',
    ipAddress: '10.0.1.20',
    device: 'Desktop',
    browser: 'Chrome 126',
    sessionId: 'ses-pqr006',
    correlationId: 'cor-025',
    durationMs: 105,
    outsideShift: false,
  },

  // 26 — Actividad fuera de horario adicional (madrugada temprana)
  {
    id: 'evt-026',
    occurredAt: '2026-07-22T03:45:00Z',
    userId: 'usr-04',
    userName: 'Andrea Torres',
    userEmail: 'andrea.torres@4guard.mx',
    userRole: 'SHIFT_LEADER',
    organizationId: 'org-01',
    warehouseId: 'wh-03',
    warehouseName: 'Guadalajara',
    module: 'Recepción',
    action: 'CREATE_RECEIPT',
    entityType: 'ASN',
    entityId: 'ASN-00312',
    description: 'Creó recepción de emergencia ASN-00312 durante madrugada.',
    result: 'SUCCESS',
    severity: 'HIGH',
    reason: 'Recepción de emergencia autorizada por gerencia',
    newValues: { asn: 'ASN-00312', lines: 12, status: 'OPEN' },
    ipAddress: '172.16.0.55',
    device: 'Mobile',
    browser: 'Chrome Mobile',
    sessionId: 'ses-emergency015',
    correlationId: 'cor-026',
    durationMs: 890,
    outsideShift: true,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// PERFILES DE REPORTE (4 perfiles de muestra)
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_REPORT_PROFILES: ActivityReportProfile[] = [
  {
    id: 'prof-001',
    code: 'RPT-USR-001',
    name: 'Actividad crítica diaria',
    description: 'Vista rápida de todas las operaciones críticas y errores del día.',
    ownerId: 'usr-03',
    visibility: 'SHARED',
    status: 'ACTIVE',
    warehouseIds: ['wh-01', 'wh-02', 'wh-03'],
    modules: ['Inventario', 'Embarques', 'Calidad'],
    actions: ['BLOCK_LOT', 'CANCEL_SHIPMENT', 'CRITICAL_ACTION'],
    results: ['ERROR', 'REJECTED'],
    severities: ['HIGH', 'CRITICAL'],
    visibleColumns: ['occurredAt', 'userName', 'module', 'action', 'result', 'severity'],
    defaultDateRange: 'TODAY',
    defaultView: 'TABLE',
    exportFormat: 'XLSX',
    createdAt: '2026-07-01T09:00:00Z',
    updatedAt: '2026-07-15T10:30:00Z',
  },
  {
    id: 'prof-002',
    code: 'RPT-USR-002',
    name: 'Monitoreo de autenticación',
    description: 'Seguimiento de logins fallidos y logouts fuera de horario.',
    ownerId: 'usr-03',
    visibility: 'SHARED',
    status: 'ACTIVE',
    warehouseIds: ['wh-01', 'wh-02', 'wh-03'],
    modules: ['Autenticación'],
    actions: ['LOGIN', 'LOGIN_FAILED', 'LOGOUT'],
    results: ['SUCCESS', 'REJECTED', 'ERROR'],
    severities: ['INFO', 'MEDIUM', 'HIGH', 'CRITICAL'],
    visibleColumns: ['occurredAt', 'userName', 'userRole', 'action', 'result', 'ipAddress'],
    defaultDateRange: 'LAST_7_DAYS',
    defaultView: 'TIMELINE',
    exportFormat: 'CSV',
    createdAt: '2026-07-05T11:00:00Z',
    updatedAt: '2026-07-20T08:00:00Z',
  },
  {
    id: 'prof-003',
    code: 'RPT-USR-003',
    name: 'Actividad fuera de turno',
    description: 'Reporte personal de acciones ejecutadas fuera del horario regular.',
    ownerId: 'usr-06',
    visibility: 'PRIVATE',
    status: 'ACTIVE',
    warehouseIds: ['wh-02'],
    modules: [],
    actions: [],
    results: ['SUCCESS', 'WARNING', 'ERROR', 'REJECTED'],
    severities: ['INFO', 'MEDIUM', 'HIGH', 'CRITICAL'],
    visibleColumns: ['occurredAt', 'userName', 'module', 'action', 'description', 'result'],
    defaultDateRange: 'LAST_7_DAYS',
    defaultView: 'TABLE',
    exportFormat: 'PDF',
    createdAt: '2026-07-10T14:00:00Z',
    updatedAt: '2026-07-10T14:00:00Z',
  },
  {
    id: 'prof-004',
    code: 'RPT-USR-004',
    name: 'Reporte de calidad e inventario',
    description: 'Revisión mensual de operaciones de calidad y ajustes de inventario.',
    ownerId: 'usr-03',
    visibility: 'SHARED',
    status: 'INACTIVE',
    warehouseIds: ['wh-01', 'wh-02'],
    modules: ['Calidad', 'Inventario'],
    actions: ['BLOCK_LOT', 'ADJUST_INVENTORY', 'CHANGE_LOCATION'],
    results: ['SUCCESS', 'WARNING'],
    severities: ['MEDIUM', 'HIGH', 'CRITICAL'],
    visibleColumns: ['occurredAt', 'userName', 'module', 'action', 'entityType', 'entityId', 'result', 'severity'],
    defaultDateRange: 'CUSTOM',
    defaultView: 'TABLE',
    exportFormat: 'XLSX',
    createdAt: '2026-06-01T09:00:00Z',
    updatedAt: '2026-07-01T00:00:00Z',
  },
];
